[versions]
kotlinx-io = "0.8.0"

gradle-dokka = "2.0.0"
gradle-jgitver = "0.10.0-rc03"
gradle-mavenPublish = "0.33.0"
gradle-mkdocs = "4.0.1"
gradle-spotless = "7.0.4"
gradle-kover = "0.9.1"
tool-prettier = "3.6.2"

# Upgrade this in sync with Gradle and JDK
gradle-kotlin = "2.2.0"

# Don't forget to check settings.gradle for more versions

[libraries]
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinx-io" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "gradle-dokka" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version.ref = "gradle-jgitver" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "gradle-kover" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-mavenPublish" }
mkdocs = { id = "ru.vyarus.mkdocs-build", version.ref = "gradle-mkdocs" }
spotless = { id = "com.diffplug.spotless", version.ref = "gradle-spotless" }
